shipwright-io/setup@main
shipwright-io/cli pull request #155
Opened 2022-11-18 17:08 UTC by otaviof

# Changes

Adopting shipwright-io/setup to prepare the environment for e2e tests, removed redundant scripts.

# Submitter Checklist

- [x] ~Includes tests if functionality changed/was added~
- [x] Includes docs if changes are user-facing
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [x] Release notes block has been filled in, or marked NONE

# Release Notes

```release-note
NONE
```

2022-11-18 18:47 UTC, otaviof commented
/retitle BUILD-522: shipwright-io/setup@main

2022-11-18 18:59 UTC, otaviof commented
/assign @SaschaSchwarze0

2022-12-05 17:55 UTC, otaviof commented
/retitle BUILD-522: shipwright-io/setup@v1

2022-12-06 08:58 UTC, HeavyWombat requested changes
Awesome! Thank you for this initiative to simplify the setup and to make it usable in other repositories as well. I just have one remark where I would like to hear what you think.

2022-12-06 08:58 UTC, HeavyWombat commented on .github/workflows/e2e.yaml
> +      - uses: ./.github/actions/setup
Nit: We could improve readability of the CI result page by giving this composite a name I think. What do you think?

<img width="321" alt="image" src="https://user-images.githubusercontent.com/1979133/205865860-e3fe2ddb-6ee3-4c84-baf9-11868d2944fc.png">

```suggestion
      - name: Setup Go and ko
        uses: ./.github/actions/setup
```

2022-12-11 12:59 UTC, SaschaSchwarze0 approved these changes
/approve
/lgtm

2022-12-11 13:05 UTC, merged