adding .adoc files for documentation
shipwright-io/cli pull request #186
Opened 2023-06-22 06:09 UTC by vinagarw272001

# Changes

# Submitter Checklist

- [ ] Includes tests if functionality changed/was added
- [ ] Includes docs if changes are user-facing
- [ ] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [ ] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

2023-06-22 11:49 UTC, otaviof requested changes
Nice one, @vinagarw272001!

2023-06-22 11:49 UTC, otaviof commented on docs-adoc/local_source_upload.adoc
@vinagarw272001 could you please use `git mv` to mark those files as renamed?

2023-06-26 12:56 UTC, otaviof commented
The reason for this change is shared [here](https://github.com/shipwright-io/build/pull/1324#issuecomment-1607410801), please consider.

2023-08-14 23:56 UTC, coreydaley commented
/close
discussed by community and decided against it

2023-08-14 23:56 UTC, closed without merging