Fix `gocritic` findings
shipwright-io/cli pull request #292
Opened 2024-12-16 14:49 UTC by HeavyWombat

# Changes

While working on https://github.com/shipwright-io/cli/pull/291, I realized that my [linter](https://github.com/go-critic/go-critic) returned some minor findings in this repository.

Fix minor TYPO in `hack/verify-docs.sh`.

Resolve `gocritic` findings.

Remove trailing whitespaces.

# Submitter Checklist

- [ ] Includes tests if functionality changed/was added
- [ ] Includes docs if changes are user-facing
- [X] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)
- [X] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

```release-note
NONE
```

2024-12-16 14:50 UTC, HeavyWombat commented on pkg/shp/cmd/buildrun/logs.go
> +		for _, container := range append(pod.Spec.InitContainers, pod.Spec.Containers...) {
```
./pkg/shp/cmd/buildrun/logs.go:113:17: appendAssign: append result not assigned to the same slice
```

2024-12-16 14:50 UTC, HeavyWombat commented on pkg/shp/cmd/follower/follow.go
> +	for _, container := range append(pod.Spec.InitContainers, pod.Spec.Containers...) {
```
./pkg/shp/cmd/follower/follow.go:110:16: appendAssign: append result not assigned to the same slice
```

2024-12-16 14:51 UTC, HeavyWombat commented on pkg/shp/reactor/pod_watcher.go
> -	//defer p.stopLock.Unlock()
Probably unused by now.

2024-12-16 14:51 UTC, HeavyWombat commented on pkg/shp/streamer/util.go
> +	return strings.TrimPrefix(strings.ReplaceAll(fpath, prefix, ""), string(filepath.Separator))
```
./pkg/shp/streamer/util.go:21:28: wrapperFunc: use strings.ReplaceAll method in `strings.Replace(fpath, prefix, "", -1)`
```

2024-12-24 11:19 UTC, SaschaSchwarze0 requested changes
Thanks, looks good. Do you mind enabling the linter in `.golangci.yml`. Otherwise it won't take too long for new findings.

2025-01-07 16:14 UTC, SaschaSchwarze0 approved these changes
/approve
/lgtm

2025-01-07 16:36 UTC, merged