Bootstrapping End-to-End Tests
shipwright-io/cli pull request #40
Opened 2021-09-21 08:10 UTC by otaviof

# Changes

This pull-requests introduces the machinery to run end-to-end tests, as described on the [enhancement-proposal](https://github.com/shipwright-io/build/blob/main/docs/proposals/cli.md#testing). That means the following components are ready to use:

- `make verify-kind`: assure KinD's node is ready
- `make install-shipwright`: deploys Tekton and Shipwright Build Controller using the versions specified on the Makefile
- `make test-e2e`: runs the end-to-end tests under `./test/e2e` directory

And Github Action has been updated to use those new targets, and let [BATs](https://github.com/bats-core/bats-core) available

# Submitter Checklist

- [x] Includes tests if functionality changed/was added
- [x] ~Includes docs if changes are user-facing~
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [x] Release notes block has been filled in, or marked NONE

# Release Notes

```release-note
NONE
```

2021-09-21 08:12 UTC, otaviof commented
@gabemontero as we've spoken yesterday, here goes the initial scaffolding for end-to-end testing, please consider.

/assign @gabemontero @adambkaplan @coreydaley @HeavyWombat

2021-09-21 14:56 UTC, adambkaplan requested changes
Language change requested, otherwise looks good.

2021-09-21 14:56 UTC, adambkaplan commented on test/e2e/helpers.sh
> +}
"die" might be considered exclusionary language, in the same category as "kill." I would replace this with "fail"
```suggestion
function fail () {
	echo $* >&2
	exit 1
}
```

2021-09-21 14:56 UTC, adambkaplan commented on test/e2e/helpers.sh
> +		die "Unable to find '${BIN}' executable"
```suggestion
		fail "Unable to find '${BIN}' executable"
```

2021-09-21 17:20 UTC, gabemontero commented
I take that back  .... https://github.com/shipwright-io/cli/pull/40/checks?check_run_id=3661400810

I'm having a tough time missing items in shipwright PRs today :-/

2021-09-21 17:29 UTC, gabemontero commented
One more req @otaviof .... an update to this REPO's readme or some new markdown doc that explains how to add e2e's to the e2e bats file would be good.

WDYT?

2021-09-21 17:48 UTC, gabemontero commented
> One more req @otaviof .... an update to this REPO's readme or some new markdown doc that explains how to add e2e's to the e2e bats file would be good.
> 
> WDYT?

in a follow up to https://github.com/shipwright-io/cli/pull/39 I'll take a stab and adding end to end tests for `shp build run <name> --follow`

extra credit will be cancel builds (that one is trickier given the timing windows needed), but we'll see how long it takes to do ^^

2021-09-22 06:01 UTC, otaviof commented
> One more req @otaviof .... an update to this REPO's readme or some new markdown doc that explains how to add e2e's to the e2e bats file would be good.
> 
> WDYT?

Good idea! I just pushed the new documentation bits, I'm starting a `docs/testing.md` files to describe the details and show an example of how BATS should be used. Please consider :-)

2021-09-22 11:54 UTC, gabemontero requested changes
Some wording suggestions for the new testing.md doc, but generally looks great @otaviof !

Assuming you agree with my suggestions, I'll lgtm after you have made the updates.

2021-09-22 11:54 UTC, gabemontero commented on docs/testing.md
> +invoking one of those targets to test current changes.
invoking -> invoke

2021-09-22 11:54 UTC, gabemontero commented on docs/testing.md
> +End-to-End tests aim to mimic the real world usage this CLI against the [Shipwright Build
usage this -> usage of this

2021-09-22 11:54 UTC, gabemontero commented on docs/testing.md
> +Controller][shipwrightBuild]. To run end-to-end tests make sure a newly binary is compiled (`make
a newly binary is compiled -> you have compiled your latest changes to the binary

2021-09-22 11:54 UTC, gabemontero commented on docs/testing.md
> +Before testing a [KinD][kindSig] instance is created, it runs a predefined version of Kubernetes,
it runs -> running

put a period instead of a comma Kubernetes

2021-09-22 11:54 UTC, gabemontero commented on docs/testing.md
> +please consider [GitHub Action files](../.github/workflows/e2e.yaml) for more details. Additionally,
capitalize please

2021-09-22 11:54 UTC, gabemontero commented on docs/testing.md
> +`kubectl` is required to intereact with the Kubernetes Cluster, expected to be installed before
expected to be installed -> and you need to install it

2021-09-22 11:54 UTC, gabemontero commented on docs/testing.md
> +syntax to define test cases, collect results, and more.
Additional sentence:  "You need to install BATS before running the e2e tests".

2021-09-22 11:54 UTC, gabemontero commented on docs/testing.md
> +	oc ...
remove the oc line .... just cite kubectl for now

2021-09-22 12:52 UTC, otaviof commented
> Some wording suggestions for the new testing.md doc, but generally looks great @otaviof !
> 
> Assuming you agree with my suggestions, I'll lgtm after you have made the updates.

Thanks, @gabemontero! I'm marking all suggestions as resolved, but please consider the latest changes. Appreciated the inputs.

2021-09-22 13:05 UTC, gabemontero approved these changes
/lgtm

2021-09-22 13:05 UTC, merged