Adds support for img labels and anno. in build create cmd
shipwright-io/cli pull request #68
Opened 2021-10-29 10:39 UTC by sm43

This adds support to specify labels and annotation for
output image.
There are 2 flags added for the `build create` command
- output-image-label
- output-image-annotation

Part of #66 

Signed-off-by: Shivam Mukhade <smukhade@redhat.com>

# Changes

# Submitter Checklist

- [x] Includes tests if functionality changed/was added
- [ ] Includes docs if changes are user-facing
- [x] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [x] Release notes block has been filled in, or marked NONE

See [the contributor guide](https://github.com/shipwright-io/build/blob/main/CONTRIBUTING.md)
for details on coding conventions, github and prow interactions, and the code review process.

# Release Notes

```release-note
Adds support to specify on Build objects labels and annotations to be set on output images
```

2021-10-30 04:07 UTC, sm43 commented
@gabemontero Thanks for release notes 🙂 will keep in mind to fill it from next time. 
e2e framework used is new for me so will address the e2e test in a follow up PR.

2021-11-02 04:11 UTC, sm43 commented
/hold
will try adding e2e!

2021-11-02 04:33 UTC, sm43 commented
/hold cancel
@gabemontero added a e2e test, ptal.

2021-11-02 10:04 UTC, otaviof requested changes
I would rather pursue the [`pflag.Value` approach](https://github.com/spf13/pflag/blob/d5e0c0615acee7028e1e2740a11102313be88de1/flag.go#L185-L191), so we can keep `flags` package responsible for providing a `BuildSpec`/`BuildRunSpec` without side effects, improved testability and more.

Please consider the changes in #69, and the [example usage of `flags` package](https://github.com/shipwright-io/cli/blob/d04b9eabeb5ce03425a461516b5dd2121340b89f/pkg/shp/flags/doc.go).

2021-11-02 16:16 UTC, sm43 commented
> I would rather pursue the [`pflag.Value` approach](https://github.com/spf13/pflag/blob/d5e0c0615acee7028e1e2740a11102313be88de1/flag.go#L185-L191), so we can keep `flags` package responsible for providing a `BuildSpec`/`BuildRunSpec` without side effects, improved testability and more.
> 
> Please consider the changes in #69, and the [example usage of `flags` package](https://github.com/shipwright-io/cli/blob/d04b9eabeb5ce03425a461516b5dd2121340b89f/pkg/shp/flags/doc.go).

Thanks @otaviof updated the pr.
cc @gabemontero

2021-11-02 17:50 UTC, otaviof reviewed
Aside of nit comments, it looks good!

/lgtm

2021-11-02 17:50 UTC, otaviof commented on pkg/shp/flags/map_value_test.go
> +	c := NewMapValue(spec.Output.Labels)
nit: rename this variable to `m` it follows the original type.

2021-11-02 17:50 UTC, otaviof commented on test/e2e/output-image-labels-annotations.bats
> +@test "shp output image labels and annotation lifecycle" {
great, thank you!

2021-11-02 17:50 UTC, otaviof commented on pkg/shp/flags/map_value.go
> +func (c *MapValue) Type() string {
nit: rename `c` to `_`, since it's not in use.

2021-11-02 17:50 UTC, otaviof commented on pkg/shp/flags/flags.go
> +
nit: remove empty line.

2021-11-02 17:51 UTC, merged