Auto-generate markdown documentation
shipwright-io/cli pull request #94
Opened 2022-01-29 06:56 UTC by kevydotvinu

# Changes

Auto-generate markdown documentation using the [cobra library](https://github.com/spf13/cobra/blob/master/doc/md_docs.md).

Fixes #14 

# Submitter Checklist

- [ ] Includes tests if functionality changed/was added
- [ ] Includes docs if changes are user-facing
- [ ] [Set a kind label on this PR](https://prow.k8s.io/command-help#kind)  
- [ ] Release notes block has been filled in, or marked NONE

# Release Notes

```release-note
NONE
```

2022-02-02 09:16 UTC, otaviof requested changes
Cool initiative, thanks! Please consider the review comment, that's my only remark.

2022-02-02 09:16 UTC, otaviof commented on docs/shp.md
> +      --cache-dir string               Default cache directory (default "/home/vkochuku/.kube/cache")
During the processing of the Cobra commands, the `cache-dir` is being extended and therefore your home folder path is shown as part of the documentation. Please, check how we could have something like `~/.kube/cache` instead.

2022-02-14 15:39 UTC, gabemontero commented
/assign @adambkaplan 

since he created the issue being fixed

2022-02-14 15:39 UTC, gabemontero commented
/assign @otaviof 

since he provided  a review previously

2022-02-24 08:58 UTC, otaviof commented
@kevydotvinu after we finish with the amends, please squash all the changes in two commits. The first with general code changes, and the second with the generated markdown files.

2022-03-01 04:35 UTC, kevydotvinu commented
> @kevydotvinu after we finish with the amends, please squash all the changes in two commits. The first with general code changes, and the second with the generated markdown files.

Thanks @otaviof :+1: Appreciate your continuous help :smile: Please review the changes and let me know if anything else to be added/changed.

2022-03-01 11:36 UTC, otaviof commented
/lgtm
/approve

Thank you indeed, @kevydotvinu!

2022-03-01 11:37 UTC, otaviof approved these changes

2022-03-01 11:37 UTC, merged